// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tablec_string
std::unordered_map<SEXP, int> tablec_string(CharacterVector x);
RcppExport SEXP _trqwe_tablec_string(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(tablec_string(x));
    return rcpp_result_gen;
END_RCPP
}
// tablec_int
std::unordered_map<int, int> tablec_int(IntegerVector x);
RcppExport SEXP _trqwe_tablec_int(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(tablec_int(x));
    return rcpp_result_gen;
END_RCPP
}
// tablec_factor
IntegerVector tablec_factor(IntegerVector x);
RcppExport SEXP _trqwe_tablec_factor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(tablec_factor(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_euclidean_dist
NumericMatrix fast_euclidean_dist(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _trqwe_fast_euclidean_dist(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_euclidean_dist(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_trqwe_tablec_string", (DL_FUNC) &_trqwe_tablec_string, 1},
    {"_trqwe_tablec_int", (DL_FUNC) &_trqwe_tablec_int, 1},
    {"_trqwe_tablec_factor", (DL_FUNC) &_trqwe_tablec_factor, 1},
    {"_trqwe_fast_euclidean_dist", (DL_FUNC) &_trqwe_fast_euclidean_dist, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_trqwe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
